// Generated by CoffeeScript 1.3.3
(function() {
  var Actors;

  Actors = {
    init: function(config) {
      this.config = config;
      this.setupTemplates();
      return this.bindEvents();
    },
    bindEvents: function() {
      return this.config.letterSelection.on('change', this.fetchActors);
    },
    setupTemplates: function() {
      this.config.actorListTemplate = Handlebars.compile(this.config.actorListTemplate);
      return Handlebars.registerHelper('fullName', function(actor) {
        return "" + actor.first_name + " " + actor.last_name;
      });
    },
    fetchActors: function() {
      var self;
      self = Actors;
      console.log(self.config.form.serialize());
      return $.ajax({
        url: 'index.php',
        type: 'POST',
        data: self.config.form.serialize(),
        dataType: 'json',
        success: function(results) {
          self.config.actorsList.html('');
          if (results[0]) {
            return self.config.actorsList.append(self.config.actorListTemplate(results));
          } else {
            return self.config.actorsList.append('No results found');
          }
        }
      });
    }
  };

  Actors.init({
    letterSelection: $('#q'),
    form: $('#action-selector'),
    actorListTemplate: $('#actor-list-template').html(),
    actorsList: $('ul.actors-list')
  });

}).call(this);
