// Generated by CoffeeScript 1.3.3
(function() {
  var Actors;

  Actors = {
    init: function(config) {
      this.config = config;
      this.setupTemplates();
      this.bindEvents();
      return $.ajaxSetup({
        url: 'index.php',
        type: 'POST',
        dataType: 'json'
      });
    },
    bindEvents: function() {
      this.config.letterSelection.on('change', this.fetchActors);
      this.config.actorsList.on('click', 'li', this.displayActorInfo);
      return this.config.actorInfo.on('click', 'span.close', this.closeOverlay);
    },
    setupTemplates: function() {
      this.config.actorListTemplate = Handlebars.compile(this.config.actorListTemplate);
      this.config.actorInfoTemplate = Handlebars.compile(this.config.actorInfoTemplate);
      return Handlebars.registerHelper('fullName', function(actor) {
        return "" + actor.first_name + " " + actor.last_name;
      });
    },
    fetchActors: function() {
      var self;
      self = Actors;
      return $.ajax({
        data: self.config.form.serialize(),
        success: function(results) {
          self.config.actorsList.html('');
          if (results[0]) {
            return self.config.actorsList.append(self.config.actorListTemplate(results));
          } else {
            return self.config.actorsList.append('No results found');
          }
        }
      });
    },
    displayActorInfo: function(e) {
      var self;
      self = Actors;
      self.config.actorInfo.slideUp(300);
      $.ajax({
        data: {
          actor_id: $(this).data('actor_id')
        },
        success: function(results) {}
      }).done(function(results) {
        return self.config.actorInfo.html(self.config.actorInfoTemplate(results)).slideDown(300);
      });
      return e.preventDefault();
    },
    closeOverlay: function() {
      var self;
      self = Actors;
      return self.config.actorInfo.slideUp(300);
    }
  };

  Actors.init({
    letterSelection: $('#q'),
    form: $('#action-selector'),
    actorListTemplate: $('#actor-list-template').html(),
    actorsList: $('ul.actors-list'),
    actorInfo: $('.actor-info'),
    actorInfoTemplate: $('#actor-info-template').html()
  });

}).call(this);
